[markup] ButtonPDF 컴포넌트 및 스토리북 제작
clapsheep/honeyboard-client pull request #26
Opened 2024-12-19 22:20 UTC by EliteZer0

- ButtonPDF 컴포넌트 및 스토리북 제작

## #️⃣ Issue Number

[markup] ButtonPDF 컴포넌트
[#13](https://github.com/clapsheep/honeyboard-client/issues/13)

## 📝 요약(Summary)

- PDF 다운로드 버튼 역할을 수행하는 ButtonPDF 컴포넌트를 제작했습니다.
- 스토리북을 사용하여 PDF 다운로드 버튼 클릭 상태를 확인할 수 있도록 했습니다.

## 🛠️ PR 유형

어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [x] CSS 등 사용자 UI 디자인 변경
- [x] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## 💬 공유사항 to 리뷰어

- PDF 다운로드는 버튼 내용이 변하지 않아 children을 사용하지 않고 바로 텍스트로 집어넣었는데, 이 부분에 대해서 이렇게 진행해도 될까요?
- 동시에 여러 번 눌렀을 때 파일 무제한으로 다운로드 되는 걸 방지하기 위해서 disabled를 넣었는데 필요할까요?

## ✅ PR Checklist

PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-12-20 06:03 UTC, antisdun submitted a review, later dismissed
승인합니다!

2024-12-20 07:15 UTC, clapsheep requested changes
나머지는 저번 스토리북이랑 컴포넌트 만드는 법 스터디를 안들었는데도 불구하고 너무 잘만들었어요! 제가 Request changes 보낸 부분만 체크해서 수정해주시면 좋겠습니다!

2024-12-20 07:15 UTC, clapsheep commented on src/components/atoms/ButtonPDF/ButtonPDF.stories.tsx
> +        onClick: () => alert('클릭되지 않음'),
클릭되지 않는 것을 구현하는 컴포넌트 테스트는 실제로 클릭이 안되어야합니다.
그래서 클릭 이벤트에 메세지를 그렇게 적어주는 것보다는 args:{disabled : true}를 넣어줘서 실제로 클릭이 안되는지 체크해보셔야할 것 같아요

2024-12-20 08:03 UTC, clapsheep commented on src/components/atoms/ButtonPDF/ButtonPDF.stories.tsx
> +        onClick: () => alert('클릭되지 않음'),
그리고 꼭 해당 PR에 대한 정보들을 기입해주시고 이슈랑 연결지어주세요! closes #이슈번호 하면 자동으로 pr 완료되면 이슈가 닫힙니다!

2024-12-20 08:04 UTC, clapsheep commented on src/components/atoms/ButtonPDF/ButtonPDF.stories.tsx
> +        onClick: () => alert('클릭되지 않음'),
우선은 제가 채워놨어요!

2024-12-20 09:12 UTC, EliteZer0 commented on src/components/atoms/ButtonPDF/ButtonPDF.stories.tsx
> +        onClick: () => alert('클릭되지 않음'),
> 클릭되지 않는 것을 구현하는 컴포넌트 테스트는 실제로 클릭이 안되어야합니다. 그래서 클릭 이벤트에 메세지를 그렇게 적어주는 것보다는 args:{disabled : true}를 넣어줘서 실제로 클릭이 안되는지 체크해보셔야할 것 같아요

[chore] ButtonPDF 스토리북 disabled 상태 수정
두번째 커밋에 수정해두었는데 다시 한 번 확인해보겠습니다!!

2024-12-22 15:27 UTC, clapsheep submitted a review, later dismissed

2024-12-22 15:27 UTC, clapsheep commented on src/components/atoms/TeamTag/TeamTag.tsx
> +interface User {
나중에 api 확정나면 이런 DTO에서 받은 왠만한 type은 파일 따로 빼서 폴더로 지정할게요! 그때 type이 바뀔 수 있습니다! 지금은 이렇게 임시로 하신 것 좋은 것 같아요!

2024-12-22 15:28 UTC, clapsheep commented on src/components/atoms/TeamTag/TeamTag.tsx
> +interface User {
확인하시면 Resolve conversation누르고 머지해주세요!

2024-12-23 07:45 UTC, clapsheep approved these changes

2024-12-23 07:46 UTC, merged